import Head from 'next/head'


export function Header() {
    return (
        <Head>
            <title>J-Iphone</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logoApple.png" />
        </Head>
    )
}